[package]
name = "yatima_utils"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yatima_core = { path = "../core" }
cid = "0.6.1"
multihash = "0.13.2"
multibase = "0.9.1"
multiaddr = "*"
sp-im = { path = "../sp_im" }
sp-ipld = { path = "../sp_ipld" }
sp-std = { version = "3", default-features = false }
im  = "15.0.0"
bit-vec = "0.6.3"
num-bigint = "0.3.1"
nom = "6.0.1"
nom_locate = "3.0.0"
base-x = "0.2.8"
petgraph = "0.5.1"
ropey = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[target."wasm32-unknown-unknown".dependencies]
# This is to allow for universal logging macros
wasm-bindgen = "0.2.72"
