[package]
name = "yatima-utils"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yatima-core = { path = "../core" }
yatima-runtime = { path = "../runtime" }
sp-std = { version = "3", default-features = false }
# sp-cid = { git = "https://github.com/yatima-inc/sp-cid", branch = "main" }
sp-cid = "0.1.0"
sp-multihash = { git = "https://github.com/yatima-inc/sp-multihash", branch = "main" }
sp-ipld = { git = "https://github.com/yatima-inc/sp-ipld", branch = "main" }
multibase = "0.9.1"
multiaddr = "*"
sp-im = { git = "https://github.com/yatima-inc/sp-im", branch = "main" }
sized-chunks = { git = "https://github.com/yatima-inc/sized-chunks", branch = "main", default-features = false }
bit-vec = "0.6.3"
num-bigint = "0.3.1"
nom = "6.0.1"
nom_locate = "3.0.1"
base-x = "0.2.8"
petgraph = "0.5.1"
ropey = {git = "https://github.com/yatima-inc/ropey", branch = "main"}
serde_json = { version = "1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# This is to allow for universal logging macros
wasm-bindgen = "0.2.72"
