[package]
name = "yatima-utils"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yatima-core = { path = "../core" }
sp-std = { version = "3", default-features = false }
cid = { git = "https://github.com/yatima-inc/sp-ipld", branch = "master" }
multihash = { git = "https://github.com/yatima-inc/sp-ipld", branch = "master" }
ipld = { git = "https://github.com/yatima-inc/sp-ipld", branch = "master" }
multibase = "0.9.1"
sp-im = { git = "https://github.com/yatima-inc/sp-im", branch = "main" }
im  = "15.0.0"
bit-vec = "0.6.3"
num-bigint = "0.3.1"
nom = "6.0.1"
nom_locate = "3.0.1"
base-x = "0.2.8"
petgraph = "0.5.1"
ropey = {git = "https://github.com/yatima-inc/ropey", branch = "master"}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
